### ISSUE TITLE
Crying-Counter is ready for deployment

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acm-aws#18]
[acmcsufoss/crying-counter](https://github.com/acmcsufoss/crying-counter) is ready for deployment.

cc @JustinPLee @JoelCodingWindigan @ImNotOGImOJ

**Comment by diamondburned** [comment]
Fixed in https://github.com/acmcsufoss/acm-aws/commit/19123456cc6ef13eab62665b714fe297d23def43.
